# Generated by Django 4.2 on 2023-04-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FacultyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facultyid", models.IntegerField()),
                ("facultyname", models.CharField(max_length=100)),
                ("facultyage", models.IntegerField()),
                ("researcharea", models.TextField()),
            ],
        ),
    ]
