# Generated by Django 4.2 on 2023-04-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculty", "0004_delete_award_delete_facultycomment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseInfo",
            fields=[
                ("course_id", models.IntegerField(primary_key=True, serialize=False)),
                ("course_title", models.CharField(max_length=100)),
                ("course_name", models.CharField(max_length=100)),
                ("course_section_code", models.CharField(max_length=10)),
                ("course_department", models.CharField(max_length=100)),
                ("instructor_full_name", models.CharField(max_length=100)),
            ],
        ),
    ]
