# Generated by Django 4.2 on 2023-04-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculty", "0005_courseinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentEnrollment",
            fields=[
                (
                    "enrollmentid",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("studentid", models.IntegerField()),
                ("course_id", models.IntegerField()),
            ],
        ),
    ]
