# Generated by Django 4.2 on 2023-04-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculty", "0006_studentenrollment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentenrollment",
            name="course_id",
        ),
        migrations.AddField(
            model_name="studentenrollment",
            name="course_title",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="studentenrollment",
            name="studentfirstname",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
