# Generated by Django 4.2 on 2023-04-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculty", "0007_remove_studentenrollment_course_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentenrollment",
            name="studentlastname",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
